name: AbilitiesSystem
version: '1.0-SNAPSHOT'
main: de.jonasheilig.abilitiesSystem.AbilitiesSystem
api-version: '1.21'
commands:
  heart:
    description: Set the amount of hearts for a player
    usage: /heart <player> <amount>
    permission: abilitiesSystem.heart
  setCooldown:
    description: Set the sprint cooldown time for a player
    usage: /setCooldown <player> <cooldownTime>
    permission: abilitiesSystem.setCooldown
  setSprintTime:
    description: Set the max sprint time for a player
    usage: /setSprintTime <player> <sprintTime>
    permission: abilitiesSystem.setSprintTime
  stats:
    description: Show player stats
    usage: /stats
permissions:
  abilitiesSystem.heart:
    description: Allows the player to use the /heart command
    default: op
  abilitiesSystem.setCooldown:
    description: Allows the player to set the sprint cooldown time
    default: op
  abilitiesSystem.setSprintTime:
    description: Allows the player to set the max sprint time
    default: op
